### ISSUE TITLE
3D Version

### ISSUE THREAD

**Issue by maximej** [Menshin/GGJ2020#1]
Hello, is there any way to have acess to the 3d version we can see in this article : https://www.behance.net/gallery/103568389/Eco-System

**Comment by Menshin** [comment]
Hello Maxim, the current (and last) version of EcoSystem3D is available in this very repo :
* the source code for the 3D version is basically the repo trunk and the 2D version can be found here https://github.com/Menshin/GGJ2020/tree/master/2Dversion/Assets
* compiled binaries (probably what you're looking for) can also be found here : https://github.com/Menshin/GGJ2020/releases (under the *Assets* dropmenu).

*Direct link (portable version, no install needed)* : https://github.com/Menshin/GGJ2020/releases/download/v0.1/EcoSys3D_v0.1.x86_64.zip

For what it's worth, you've been a real treat to work on, professional to the fullest even on such a small-scaled project and i'll be more than pleased to speak on this behalf should the need arise.

Wish you the best of luck,
Menshin (EcoSystem Developper)
